// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterPark.API.DbContexts;

namespace WaterPark.API.Migrations
{
    [DbContext(typeof(WaterRideContext))]
    partial class WaterRideContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WaterPark.API.Models.WaterRides", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RideAllowedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RideCost")
                        .HasColumnType("float");

                    b.Property<string>("RideName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RideAllowedTo = "Everyone",
                            RideCost = 100.0,
                            RideName = "Rain Dance"
                        },
                        new
                        {
                            Id = 2,
                            RideAllowedTo = "Adult",
                            RideCost = 150.0,
                            RideName = "Dark Slide"
                        },
                        new
                        {
                            Id = 3,
                            RideAllowedTo = "Adult",
                            RideCost = 250.0,
                            RideName = "90Degree Slide"
                        },
                        new
                        {
                            Id = 4,
                            RideAllowedTo = "Children",
                            RideCost = 75.0,
                            RideName = "Tube Way"
                        },
                        new
                        {
                            Id = 5,
                            RideAllowedTo = "Children",
                            RideCost = 150.0,
                            RideName = "Wave Pool"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
