// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTickets_API.DbContexts;

namespace MovieTickets_API.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230110061023_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieTickets_API.Models.MovieDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TicketPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("movieDetails");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            MovieName = "Bhediya",
                            MovieType = "3D",
                            ScreenNumber = 2,
                            ShowTime = new DateTime(2023, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 350.0
                        },
                        new
                        {
                            Id = 1002,
                            MovieName = "Avatar: The Way of Water",
                            MovieType = "4D",
                            ScreenNumber = 3,
                            ShowTime = new DateTime(2023, 1, 10, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 480.0
                        },
                        new
                        {
                            Id = 1003,
                            MovieName = "Ved",
                            MovieType = "3D",
                            ScreenNumber = 1,
                            ShowTime = new DateTime(2023, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 275.0
                        },
                        new
                        {
                            Id = 1004,
                            MovieName = "Cirkus",
                            MovieType = "2D",
                            ScreenNumber = 3,
                            ShowTime = new DateTime(2023, 1, 10, 2, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 300.0
                        },
                        new
                        {
                            Id = 1005,
                            MovieName = "Drishyam 2",
                            MovieType = "2D",
                            ScreenNumber = 1,
                            ShowTime = new DateTime(2023, 1, 10, 1, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 350.0
                        },
                        new
                        {
                            Id = 1006,
                            MovieName = "Vikram",
                            MovieType = "2D",
                            ScreenNumber = 2,
                            ShowTime = new DateTime(2023, 1, 10, 3, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 400.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
