// <auto-generated />
using System;
using Ecommerce.Api.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230110050001_IntialMigration")]
    partial class IntialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecommerce.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 1, 10, 10, 30, 1, 467, DateTimeKind.Local).AddTicks(77),
                            DisplayOrder = 1,
                            Title = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 1, 10, 10, 30, 1, 469, DateTimeKind.Local).AddTicks(4959),
                            DisplayOrder = 2,
                            Title = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 1, 10, 10, 30, 1, 469, DateTimeKind.Local).AddTicks(5010),
                            DisplayOrder = 3,
                            Title = "Motorola"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 1, 10, 10, 30, 1, 469, DateTimeKind.Local).AddTicks(5013),
                            DisplayOrder = 4,
                            Title = "Nokia"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 1, 10, 10, 30, 1, 469, DateTimeKind.Local).AddTicks(5014),
                            DisplayOrder = 5,
                            Title = "RealMe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
